name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Bu iş akışının sadece Dependabot tarafından açılan PR'larda çalışmasını sağlar
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Enable auto-merge for Dependabot PRs
        # İsteğe bağlı: Yalnızca 'patch' (yama) veya 'minor' (küçük) güncellemeleri otomatik birleştirir, 
        # 'major' (büyük) güncellemeleri senin manuel kontrolüne bırakır. 
        # (Eğer tümünü birleştirmek istersen alt satırı silebilir veya yorum satırı yapabilirsin)
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}